### ISSUE TITLE
Got this crash as soon as i went to the surface (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by XanderCreates** [Haven-King/Atmosfera#24]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/22/21, 1:27 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at net.minecraft.class_359.method_1957(class_359.java:64)
	at net.minecraft.class_329.method_1753(class_329.java:396)
	at net.minecraft.class_757.method_3192(class_757.java:1210)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	
	Version:
	
	1.17.1
	
	OS: Win 10
	
	Java: OpenJDK 16

**Comment by XanderCreates** [comment]
[crash-2021-07-22_01.27.50-client.txt](https://github.com/Haven-King/Atmosfera/files/6860151/crash-2021-07-22_01.27.50-client.txt)

**Comment by Zetabite** [comment]
There wont be any fixes. 1.4.2 is end of life, only a question of time till Haven updates to 2.0.0

**Comment by XanderCreates** [comment]
Ok I guess this mod is unplayable then

**Comment by XanderCreates** [comment]
Well, at this time that is

> Ok I guess this mod makes the game unplayable then

**Comment by XanderCreates** [comment]
Seems to have been fixed in 2.0.0
